services:
  postgres:
    image: postgres:16
    container_name: postgres_scorer
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scorer_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scorer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
